# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_score', models.IntegerField(default=0)),
                ('opinion', models.TextField(max_length=3000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('popularity_score', models.IntegerField(default=0)),
                ('is_company', models.BooleanField(default=False)),
                ('top_con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_con', to='chooseASide.Thought')),
                ('top_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_pro', to='chooseASide.Thought')),
            ],
        ),
        migrations.AddField(
            model_name='thought',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chooseASide.Topic'),
        ),
    ]
