# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='top_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_con', to='chooseASide.Thought'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='top_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_pro', to='chooseASide.Thought'),
        ),
    ]
