# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0002_auto_20160728_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 28, 20, 15, 14, 372268, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
