# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0003_topic_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='identifier1',
            field=models.CharField(default='', help_text='Ip address of the user', max_length=20),
        ),
        migrations.AddField(
            model_name='thought',
            name='identifier2',
            field=models.CharField(default='', help_text='Device user is posting from', max_length=30),
        ),
    ]
