# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0004_auto_20160728_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='identifier1',
            field=models.CharField(default='', help_text='Ip address of the user', max_length=200),
        ),
    ]
