# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0005_auto_20160728_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='pro_or_con',
            field=models.BooleanField(default=True, help_text='True is for and on the left, False is against and on the right'),
            preserve_default=False,
        ),
    ]
