# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0007_topic_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='agree_score',
            new_name='score',
        ),
    ]
