# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0008_auto_20160729_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
