# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0009_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='opinion',
            field=models.TextField(max_length=6000),
        ),
    ]
