# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0010_auto_20160729_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='identifier2',
            field=models.CharField(default='', help_text='Device user is posting from', max_length=200),
        ),
    ]
