# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0012_auto_20160729_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
