# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0013_auto_20160729_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='expired',
        ),
    ]
