# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chooseASide', '0014_remove_topic_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='expired',
        ),
    ]
